# Generated by Django 6.0.4 on 2026-04-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timeout', models.IntegerField(help_text='Timeout in seconds')),
                ('alert_email', models.EmailField(max_length=254)),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('down', 'Down'), ('paused', 'Paused')], default='active', max_length=10)),
            ],
        ),
    ]
