# Generated by Django 6.0.4 on 2026-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
