# Generated by Django 6.0.4 on 2026-04-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_monitor_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='timeout',
            field=models.IntegerField(default=60),
        ),
    ]
