# Generated by Django 6.0.4 on 2026-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
